version: '2.1'

services:
  db-museum:
    image: db-museum:latest
    networks:
      - museum-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 1001:5432
    container_name: db-museum
  backend:
    image: backend:latest
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - DB_USERS_HOST=db-museum
      - DB_USERS_PORT=5432
      - DB_USERS_USER=postgres
      - DB_USERS_DBNAME=postgres
      - DB_USERS_PASSWORD=postgres
      - DB_USERS_SSL=disable
    depends_on:
      - db-museum
    networks:
      - museum-network

networks:
  museum-network:
    name: museum-network
